/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.58
 * Generated at: 2020-10-12 10:08:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1602497169952L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- \r\n");
      out.write("\t\r\n");
      out.write("\t\t1. 회원 서비스\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t|  C(INSERT)\t| R(SELECT) | U(UPDATE) | D(DELETE)\r\n");
      out.write("\t\t=========================================================================\r\n");
      out.write("\t\t\t\t로그인\t|\t\t\t\t|\t  O\t\t|\t\t\t|\r\n");
      out.write("\t\t\t\t회원가입 \t|\t    O \t    |\t\t\t|\t\t\t|\r\n");
      out.write("\t\t\t[아이디중복체크]\t|\t\t\t\t|\t  O\t\t| \t\t\t|\t\r\n");
      out.write("\t\t\t\t마이페이지   |\t\t\t\t|\t  O\t\t|\t\t\t|\r\n");
      out.write("\t\t\t\t정보수정\t|\t\t\t\t|\t\t\t|\t  O\t\t|\r\n");
      out.write("\t\t\t\t회원탈퇴\t|\t\t\t\t|\t\t\t|\t  O\t\t|\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t2. 공지사항 서비스\r\n");
      out.write("\t\t\t공지사항리스트조회(R)/ 상세조회 (R)\r\n");
      out.write("\t\t\t공지사항작성하기(C)/공지사항수정하기(U)/ 공지사항삭제하기(U)\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t3. 일반게시판 서비스\r\n");
      out.write("\t\t\t게시판리스트조회(R)+페이징처리/ 상세조회(R)\r\n");
      out.write("\t\t\t게시판작성하기(C)+첨부파일업로드/게시판수정하기(U) / 게시판삭제하기(U)\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t[댓글리스트조회(R) /댓글작성하기(C)]\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t4. 사진게시판 서비스\r\n");
      out.write("\t\t\t썸네일리스트조회(R)/ 상세조회(R)\r\n");
      out.write("\t\t\t게시판작성하기(C) + 첨부파일(다중)업로드\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t -->\r\n");
      out.write("\t \r\n");
      out.write("\t ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("        #loginForm, #userInfo{float:right}\r\n");
      out.write("        #userInfo a{\r\n");
      out.write("            color:black;\r\n");
      out.write("            text-decoration:none;\r\n");
      out.write("            font-size:11px;\r\n");
      out.write("        }\r\n");
      out.write("        .navWrap{background:black}\r\n");
      out.write("        .menu{\r\n");
      out.write("            display:table-cell;\r\n");
      out.write("            height:50px;\r\n");
      out.write("            width:150px;\r\n");
      out.write("        }\r\n");
      out.write("        .menu a{\r\n");
      out.write("            text-decoration:none;\r\n");
      out.write("            color:white;\r\n");
      out.write("            font-weight:bold;\r\n");
      out.write("            display:block;\r\n");
      out.write("            width:100%;\r\n");
      out.write("            height:100%;\r\n");
      out.write("            font-size:20px;\r\n");
      out.write("            line-height:50px;\r\n");
      out.write("        }\r\n");
      out.write("        .menu a:hover{\r\n");
      out.write("            background:darkgray;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1 align =\"center\">Welcome JSP World!</h1>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"loginArea\">\r\n");
      out.write("        <!-- 1. 로그인 전에 보여지는 로그인 form  -->\r\n");
      out.write("\r\n");
      out.write("        <form id=\"loginForm\" action=\"/jsp/login.me\" method=\"post\">\r\n");
      out.write("            \r\n");
      out.write("            <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th><label for=\"userId\">아이디 </label></th>\r\n");
      out.write("                <td><input type=\"text\" id=\"userId\" name=\"userId\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th><label for =\"userPwd\">비밀변호 </label></th>\r\n");
      out.write("                <td><input type=\"password\" id=\"userPwd\" name=\"userPwd\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th colspan=\"2\">\r\n");
      out.write("                    <button type=\"submit\">로그인</button>\r\n");
      out.write("                    <button type=\"button\">회원가입</button>\r\n");
      out.write("                </th>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <!-- 2. 로그인 성공 후 보여지는 div -->\r\n");
      out.write("        \r\n");
      out.write("            <!-- <div id=\"userInfo\">\r\n");
      out.write("                <b>xxx님 </b>의 방문을 환영합니다<div class=\"\">\r\n");
      out.write("                    <div align=\"center\">\r\n");
      out.write("                        <a href=\"\">마이페이지</a>\r\n");
      out.write("                        <a href=\"\">로그아웃</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <br><br><Br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navWrap\">\r\n");
      out.write("        <div class=\"menu\"><a href=\"\">HOME</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"\">공지사항</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"\">일반게시판</a></div>\r\n");
      out.write("        <div class=\"menu\"><a href=\"\">사진게시판</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
